[package]
edition = "2021"
name = "service"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prisma-client-rust = {git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.0"}
